version: '3'

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # Expose dashboard
      - "8080:8080"

    volumes:
      - ./:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
